### ISSUE TITLE
Error: Representation {id} not found

### ISSUE THREAD

**Issue by smaznet** [fent/node-m3u8stream#52] opened 2020-01-01 11:16 UTC
https://github.com/fent/node-m3u8stream/blob/f19d7e68f669def5c12854b755c0f3e9e61fb0ca/src/dash-mpd-parser.ts#L82

i think problem is in this line why you converting to string?

**Comment by fent** [comment] 2020-01-01 22:29
dupe of https://github.com/fent/node-m3u8stream/issues/25

**Closed by fent** 2020-01-01 22:29 UTC
Labels: duplicate
